version: '3.8'

networks:
  book-net:
    driver: bridge

services: 
  mysqldb:
    image: mysql
    container_name: book_mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_HOST: $MYSQL_ROOT_HOST
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/backup/:/data_backup/data
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
              --default-authentication-plugin=mysql_native_password
    networks:
      - book-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysqldb
    networks:
      - book-net
    ports:
      - "$PMA_LOCAL_PORT:$PMA_DOCKER_PORT"
    environment:
      - PMA_HOST=book_mysql
      - PMA_PORT=$MYSQL_DOCKER_PORT
    volumes:
      - /sessions
    container_name: book_phpmyadmin
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    container_name: book_app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
      - ./mysql/BOOKCOMMUNITY.sql:/database/BOOKCOMMUNITY.sql
      - /app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks: 
      - book-net


volumes: 
  # db-config:
  db-data: 